### ISSUE TITLE
Intro to state in Compose: Android Basics with Compose

### ISSUE THREAD

**Issue by jsmecha** [google-developer-training/basic-android-kotlin-compose-training-tip-calculator#105]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-compose-using-state?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-compose-unit-2-pathway-3%3Fhl%3Dko%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-compose-using-state#7

**In which task and step of the codelab can this issue be found?**
task : adding TextField 
**Describe the problem**
I already did import "androidx.compose.material3.TextField" , sync project with gridle and rebuild, but
errors aren't resolved.
the error is "This material API is experimental and is likely to change or to be removed in the future"

**Steps to reproduce?**
1. Go to...
2. Click on...
3. See error...

**Versions**
_Android Studio version:_ Flamingo 2022.2.1 Patch 1 runtime version 17.0.6
_API version of the emulator:_ 33
material3:1.0.1

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by Jacqueries** [comment]
I have the same issue.
Adding `@ExperimentalMaterial3Api` before the function remove the issues, but it dosen't seem like the true solution ...

**Comment by android-dev-lxl** [comment]
@Jacqueries 
@jsmecha 
Thank you for reaching out to us.
For now adding @ExperimentalMaterial3Api before the function is one of the temporary solution till the API is stable.
