### ISSUE TITLE
Intro to state in Compose: Android Basics with Compose

### ISSUE THREAD

**Issue by AndrejaN** [google-developer-training/basic-android-kotlin-compose-training-tip-calculator#107]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-compose-using-state?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-compose-unit-2-pathway-3%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-compose-using-state#5

**In which task and step of the codelab can this issue be found?**
Task 6, before executing Step 4

**Describe the problem**
The correct defintion of the EditNumberField should fun EditNumberField(modifier: Modifier = Modifier) to pass the modifier from the TextField. 
In the offical web site the code is without the function parameter, which will results in error.

**Steps to reproduce?**
1. Copy the offical code given in the excerise: 
2. @Composable
fun EditNumberField() {
   var amountInput by remember { mutableStateOf("") }
   TextField(
       value = amountInput,
       onValueChange = { amountInput = it },
       modifier = modifier
   )
}
3. Click on "Run app"
4. See error... =>"Cannot find a parameter with this name: modifier"

**Versions**
Android Studio version: 2023.1.1 Canary 3
API version of the emulator: 30 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by android-dev-lxl** [comment]
@AndrejaN 
Thank you so much for reporting this issue. This is fixed and will be published soon.
