### ISSUE TITLE
Write automated tests: Android Basics with Compose

### ISSUE THREAD

**Issue by rmswimkktt** [google-developer-training/basic-android-kotlin-compose-training-tip-calculator#108]
About Section "5. Write an instrumentation test"
`composeTestRule.onNodeWithText("Tip Percentage").performTextInput("20")` is correct, not
`composeTestRule.onNodeWithText("Tip (%)").performTextInput("20"))`.

Because
`<string name="how_was_the_service">Tip Percentage</string>`
in strings.xml

**Comment by rmswimkktt** [comment]
The source code in the zip is `composeTestRule.onNodeWithText("Tip Percentage").performTextInput("20")`,
which is the correct description.

**Comment by android-dev-lxl** [comment]
@rmswimkktt 
Fixed and to be published.
