### ISSUE TITLE
Write automated tests: Android Basics with Compose

### ISSUE THREAD

**Issue by medme** [google-developer-training/basic-android-kotlin-compose-training-tip-calculator#109]
Right:
The compiler knows that methods annotated with **@get:Rule** annotation in the androidTest directory refer to instrumentation tests and methods annotated with @Test annotation in the test directory refer to local tests.

Wrong:
The compiler knows that methods annotated with **@Test** annotation in the androidTest directory refer to instrumentation tests and methods annotated with @Test annotation in the test directory refer to local tests.

**Comment by android-dev-lxl** [comment]
@medme 
This is fixed now. Thank you for your help.
