### ISSUE TITLE
Intro to state in Compose: Android Basics with Compose

### ISSUE THREAD

**Issue by midrpostcz** [google-developer-training/basic-android-kotlin-compose-training-tip-calculator#111]
**URL of codelab**

https://developer.android.com/codelabs/basic-android-kotlin-compose-using-state?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-compose-unit-2-pathway-3%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-compose-using-state#10

**In which task and step of the codelab can this issue be found?**

Solution code, fun EditNumberField

**Describe the problem**

unresolved reference: modifier

**How to solve**

Add parameter:

**(BEFORE)**
fun EditNumberField(
    value: String,
    onValueChanged: (String) -> Unit,

**(AFTER)**
fun EditNumberField(
    value: String,
    onValueChanged: (String) -> Unit,
    modifier:Modifier

**Comment by android-dev-lxl** [comment]
@midrpostcz 
We appreciate you bringing this issue to our attention. 
But the current code in the codelab and in the solution code GitHub seems to be matching with your [AFTER] code snippet. 
Could you please explain the issue further?

<img width="1321" alt="image" src="https://github.com/google-developer-training/basic-android-kotlin-compose-training-tip-calculator/assets/24260141/733f1181-db4d-41b1-9f5f-7bea266ce7ed">
<img width="1401" alt="image" src="https://github.com/google-developer-training/basic-android-kotlin-compose-training-tip-calculator/assets/24260141/50673206-40a1-44c7-aa54-0d884efdc6a3">
