### ISSUE TITLE
Write automated tests: Android Basics with Compose

### ISSUE THREAD

**Issue by sanyamj-081** [google-developer-training/basic-android-kotlin-compose-training-tip-calculator#113]
Hi Team,

The parameter passed in the function calculateTip needs to have a comma(,) instead of a colon(:)

fun calculateTip(amount: Double, tipPercent: Double **,** roundUp: Boolean)

<img width="946" alt="Screenshot 2023-05-26 200017" src="https://github.com/google-developer-training/basic-android-kotlin-compose-training-tip-calculator/assets/104319672/d45514a0-f335-4c39-8779-08837286f28b">

**Comment by android-dev-lxl** [comment]
Duplicate of #126
