### ISSUE TITLE
Intro to state in Compose: Android Basics with Compose

### ISSUE THREAD

**Issue by SHPILEVAYAEVGENIYA** [google-developer-training/basic-android-kotlin-compose-training-tip-calculator#116]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-compose-using-state?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-compose-unit-2-pathway-3%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-compose-using-state#2

**In which task and step of the codelab can this issue be found?**
3 Get Starter Code. Step 4 Import this function: import androidx.compose.material.TextField

**Describe the problem**
When I add code:
`fun EditNumberField(modifier: Modifier = Modifier) {`
`    TextField(value = "",`
`              onValueChange = {},`
`              modifier = modifier`
`    )`
`} `
it automatically add 
import androidx.compose.**material3**.TextField
I must use material3 not just material. That's right?

**Steps to reproduce?**
1. Go to...
2. Click on...
3. See error...

**Versions**
_Android Studio version:_ 
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by android-dev-lxl** [comment]
@SHPILEVAYAEVGENIYA 
That is correct. 
Thank you so much for reporting this issue. This is fixed and will be published soon.
