### ISSUE TITLE
Calculate a custom tip: Android Basics with Compose  

### ISSUE THREAD

**Issue by diskostu** [google-developer-training/basic-android-kotlin-compose-training-tip-calculator#117]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-compose-calculate-tip

**In which task and step of the codelab can this issue be found?**
Set an action button

**Describe the problem**
There could be one little improvement for the `KeyboardOptions`. As we always want a "number" input, we could set this inside of `EditNumberField` like this:

```kotlin
@Composable
fun EditNumberField(
    @StringRes label: Int,
    keyboardOptions: KeyboardOptions,
    value: String,
    onValueChanged: (String) -> Unit,
    modifier: Modifier = Modifier
) {
    TextField(
        value = value,
        singleLine = true,
        modifier = modifier,
        onValueChange = onValueChanged,
        label = { Text(stringResource(label)) },
        keyboardOptions = keyboardOptions.copy(keyboardType = KeyboardType.Number)
    )
}
```
Then we only need to pass the value for `imeAction` when calling `EditNumberField`:
```kotlin
        EditNumberField(
            label = R.string.how_was_the_service,
            keyboardOptions = KeyboardOptions.Default.copy(
                imeAction = ImeAction.Done
            ),
            value = tipPercentageInput,
            onValueChanged = { tipPercentageInput = it },
            modifier = Modifier
                .padding(bottom = 32.dp)
                .fillMaxWidth()
        )
```

**Comment by android-dev-lxl** [comment]
@diskostu 
Thank you for reaching out to us.
This should be fixed now. 

https://github.com/google-developer-training/basic-android-kotlin-compose-training-tip-calculator/blob/main/app/src/main/java/com/example/tiptime/MainActivity.kt

<img width="689" alt="image" src="https://github.com/google-developer-training/basic-android-kotlin-compose-training-tip-calculator/assets/24260141/b813c2ae-0036-40f8-bb55-65fa7c215ff3">
