### ISSUE TITLE
Calculate a custom tip: Typo in onValueChange parameter

### ISSUE THREAD

**Issue by itxcrusher** [google-developer-training/basic-android-kotlin-compose-training-tip-calculator#123]
**URL of codelab**

https://developer.android.com/codelabs/basic-android-kotlin-compose-calculate-tip?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-compose-unit-2-pathway-3%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-compose-calculate-tip#3

**In which task and step of the codelab can this issue be found?**

Codelab - Calculate a custom tip
Step Number 04 - Add a tip-percentage text field

**Describe the problem**

The name of the lambda expression is written as "onValueChange" in some steps while in some other steps, it is written as "onValueChanged"
This minor mistake confuses a lot and it is repeated in 4-5 code samples in this step

**Steps to reproduce?**
1. Go to...Add a tip percentage text field step
2. Click on...Scroll down page
3. See error...Multiple code samples

**Versions**
_Android Studio version:_ 
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._
![Bug](https://github.com/google-developer-training/basic-android-kotlin-compose-training-tip-calculator/assets/103519535/19500a8c-a028-48d7-ba84-829019a7a3fc)

**Comment by android-dev-lxl** [comment]
@itxcrusher 
Thank you so much for reporting this issue. This is fixed and will be published soon.
