### ISSUE TITLE
Write automated tests: Android Basics with Compose

### ISSUE THREAD

**Issue by KamogaRonnieKigongo** [google-developer-training/basic-android-kotlin-compose-training-tip-calculator#124]
**fun calculateTip(amount: Double, tipPercent: Double: roundUp: Boolean)**.......this line has an issue in the code lab

**Comment by android-dev-lxl** [comment]
Duplicate of https://github.com/google-developer-training/basic-android-kotlin-compose-training-tip-calculator/issues/126
