### ISSUE TITLE
Write automated tests: Android Basics with Compose

### ISSUE THREAD

**Issue by JohnTrawolta** [google-developer-training/basic-android-kotlin-compose-training-tip-calculator#15]
There is an error when accessing to a node with the text "Cost of Service".
This text was changed to "Bill Amount".

![error1](https://user-images.githubusercontent.com/102923250/174438274-18c62b89-a54c-4e08-ab3f-6039ffaee95a.png)
![error2](https://user-images.githubusercontent.com/102923250/174438275-f26a6cc6-288e-4847-b662-3710a311f51b.png)
![error3](https://user-images.githubusercontent.com/102923250/174438277-825218f1-af39-4b7d-aa69-9ac4ff63708e.png)

**Comment by android-dev-lxl** [comment]
This should be fixed now. 
@JohnTrawolta let us know if you still face any isssues.
