### ISSUE TITLE
Intro to state in Compose: Android Basics with Compose

### ISSUE THREAD

**Issue by jh115424** [google-developer-training/basic-android-kotlin-compose-training-tip-calculator#16]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-compose-using-state?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-compose-unit-2-pathway-3%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-compose-using-state#6

**In which task and step of the codelab can this issue be found?**
    STEP 7

**Describe the problem**

1. mutableStateOf is giving a red error even though the tutorial said put it.

SEE SCREEN SHOTS

<img width="1440" alt="Screen Shot 2022-06-19 at 8 00 02 AM" src="https://user-images.githubusercontent.com/91148652/174482229-5a442492-19ff-4350-ab8b-6cc7fbe67c4a.png">

<img width="1440" alt="Screen Shot 2022-06-19 at 7 59 54 AM" src="https://user-images.githubusercontent.com/91148652/174482235-94ca6d25-cc16-4b46-9a37-c19fe06e42fd.png">

**Steps to reproduce?**
1. Go to...
2. Click on...
3. See error...

**Versions**
_Android Studio version:_ 
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by jh115424** [comment]
NEVERMIND....I GOT IT!

THANKS

**Comment by eeshvardasikcm** [comment]
Similar happened when I started using state with Kotlin Compose. Not an
uncommon issue.

**Comment by eeshvardasikcm** [comment]
State in Kotlin Compose was causing inspector to not be able to find a
suitable class to import. I had to manually enter the class imports for
hoisting. Is the documentation sufficient or is there some need to add some
notes comsidering inspections readability of the unique API depth structure
in Kotlin Compose State?

**Comment by android-dev-lxl** [comment]
@jh115424 
Glad you were able to resolve it.
