### ISSUE TITLE
Calculate a custom tip: Android Basics with Compose  

### ISSUE THREAD

**Issue by willprada** [google-developer-training/basic-android-kotlin-compose-training-tip-calculator#187]
[**URL of codelab**](https://developer.android.com/codelabs/basic-android-kotlin-compose-calculate-tip)

[6. Add a switch](https://developer.android.com/codelabs/basic-android-kotlin-compose-calculate-tip#5) - Step 5

It says:
"This table contains information about these parameters, which are the same parameters that you defined for the RoundTheTipRow() function:"

But at this point those parameters are not defined in the RounTheTipRow() function, they get defined a couple steps below at step 7

**Comment by android-dev-lxl** [comment]
@willprada 
Thank you for reaching out to us.
This is fixed and will be published soon.
