### ISSUE TITLE
Intro to state in Compose: Android Basics with Compose

### ISSUE THREAD

**Issue by EnerEkstroem** [google-developer-training/basic-android-kotlin-compose-training-tip-calculator#21]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-compose-using-state

**In which task and step of the codelab can this issue be found?**
In the section "Add the TextField composable", step 4 through 6

**Describe the problem**
I am unable to import the TextField from androidx.compose.material.TextField, I get an Unresolved reference

**Steps to reproduce?**
1. Go to...
2. Click on...
3. See error...

**Versions**
_Android Studio version:_ Chipmunk | 2021.2.1 Patch 1
_API version of the emulator:_  Pixel XL API 30

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._
![ImportError](https://user-images.githubusercontent.com/23164631/182602156-de22a540-75a0-416f-ba30-f1d991bfb2bf.PNG)

**Comment by SonwJune** [comment]
I have the same problem.
How did you solve it?

**Comment by SonwJune** [comment]
I solved this problem by updating the version of the dependent library.
![image](https://user-images.githubusercontent.com/46013679/214997526-c13818c2-b032-48e8-b6a1-857ab96ba63f.png)

**Comment by android-dev-lxl** [comment]
@EnerEkstroem 
Are you still facing this issue? 

We have updated the code to BOM. Could you test this one more time and let us know, if you are stuck.
