### ISSUE TITLE
Write automated tests: Android Basics with Compose

### ISSUE THREAD

**Issue by jrsykes** [google-developer-training/basic-android-kotlin-compose-training-tip-calculator#22]
In step 4, under "Create the test class", the instructions make it seem like there should be a preexisting 'test' directory under  app > src in provided code but there isn't. 
Have I misunderstood the instructions or is this dir missing?

**Comment by divyanshdxn** [comment]
Empty folders aren't commit to git, so it is actually not present.

BTW, your issue is a copy of https://github.com/google-developer-training/basic-android-kotlin-compose-training-tip-calculator/issues/10
Would be better if you'd consider closing this issue.
