### ISSUE TITLE
Write automated tests: Android Basics with Compose

### ISSUE THREAD

**Issue by thiccsand** [google-developer-training/basic-android-kotlin-compose-training-tip-calculator#24]
in the example code here the expected value is $2.00 but in the previous example code the real value is £2.00

**Comment by veryLazyBrain** [comment]
Hi,
I think is about the actual currency used in your country.
For exemple i'm French and I've 2,00€ 
Is probabely about this line in the function _calculateTip_ : 
return NumberFormat.getCurrencyInstance().format(tip)

try to change the return format by another function or change your expected value by £2.00. 

Bye.

**Comment by divyanshdxn** [comment]
This issue is a copy of https://github.com/google-developer-training/basic-android-kotlin-compose-training-tip-calculator/issues/20
