### ISSUE TITLE
Write automated tests: Android Basics with Compose

### ISSUE THREAD

**Issue by veryLazyBrain** [google-developer-training/basic-android-kotlin-compose-training-tip-calculator#25]
Hello
my test is failled : 

```
expected:<[$2.00]> but was:<[2,00 €]>
Expected :$2.00
Actual   :2,00 €
```

I thinks it’s related to this line in the function "calculateTip" and the langage parameter of my computer :
`
return NumberFormat.getCurrencyInstance().format(tip)`

I'm european, I juste changed the expected value "$2.00" by "2,00€"

bye.

**Comment by divyanshdxn** [comment]
This issue is a copy of https://github.com/google-developer-training/basic-android-kotlin-compose-training-tip-calculator/issues/20

**Comment by osuleymanova** [comment]
Hello @veryLazyBrain,

Thank you for reaching out to us and sharing your feedback.
As for the currency convertor, please refer to the code snippet updated:

![Screenshot 2023-01-30 at 9 22 59 AM](https://user-images.githubusercontent.com/86437155/215556554-0650022f-2195-4f30-ac23-94c251925d81.png)


Be sure that import java.text.NumberFormat is imported.
