### ISSUE TITLE
Calculate a custom tip: Android Basics with Compose  

### ISSUE THREAD

**Issue by toraarebel** [google-developer-training/basic-android-kotlin-compose-training-tip-calculator#26]
[**URL of codelab**
](https://developer.android.com/codelabs/basic-android-kotlin-compose-calculate-tip?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-compose-unit-2-pathway-3%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-compose-calculate-tip#6)

**In which task and step of the codelab can this issue be found?**
2

**Describe the problem**
The solution works as described. However, in the implementation of the RoundTheTipRow Composable, in the Row, the author uses the default Modifier instead of the passed parameter:
Row (
    modifier = Modifier  // A new Modifier
   // ...
}

vs

Row (
    modifier = modifier // The (optional) Modifier passed into the Composable
    // ...
}

Both will work, however, with the given solution,  if someone passes a Modifier to the RoundTheTipRow, it will be ignored and not used.  This is a minor thing but a bad practice and confused me for a second when working the codelab as I expected something different.

**Comment by android-dev-lxl** [comment]
@toraarebel 
Thank you for letting us know. 
This will be fixed and published soon
