### ISSUE TITLE
Write automated tests: Android Basics with Compose

### ISSUE THREAD

**Issue by mspath** [google-developer-training/basic-android-kotlin-compose-training-tip-calculator#3]
The tests will fail if the localization/currency of the developer is other than us/dollars since the expected string is hardcoded and asserts "$2.00" (both in the local and the instrumented test)

**Comment by eeshvardasikcm** [comment]
The purpose of the lesson is basic compose and kotlin learning. Is there sufficient notes or links on the webpage referencing to elsewhere for internationalization concerns? Is the current material sufficient for understanding the basic compose and kotlin concepts?

**Comment by eeshvardasikcm** [comment]
> The purpose of the lesson is basic compose and kotlin learning. Is there sufficient notes or links on the webpage referencing to elsewhere for internationalization concerns? Is the current material sufficient for understanding the basic compose and kotlin concepts?

Yes. Sufficient references and notes exist.

Yes. The lesson material scope covers the internationalization currency _unit_ issue as part of the lesson design in addition to teaching the about the _numerical value_ portion of the calculation.

 I just now had a few minutes to read the lesson at Android Basics with Compose, Calculate the tip. The subsection in this lesson called "Format the tip" adequately explains how to get the currency localized using NumberFormat.getCurrencyInstance().format(tip).

Has the test code is this repository has not been updated yet with a fix implementing _getCurrencyInstance().format(tip)_?

**Comment by osuleymanova** [comment]
Hello @mspath 

Thank you for reaching out to us and sharing your feedback.
The code snippet is updated:

![Screenshot 2023-01-30 at 9 22 59 AM](https://user-images.githubusercontent.com/86437155/215552851-b4df0d54-6152-4dc4-a9a0-d81f54c8678b.png)


Be sure that import java.text.NumberFormat is imported.

**Comment by eeshvardasikcm** [comment]
> Hello @mspath,
> 
> Thank you for reaching out to us and sharing your feedback. The code snippet is updated:
> 
> ![Screenshot 2023-01-30 at 9 22 59 AM](https://user-images.githubusercontent.com/86437155/215552851-b4df0d54-6152-4dc4-a9a0-d81f54c8678b.png)
> 
> Be sure that import java.text.NumberFormat is imported.

👍
