### ISSUE TITLE
Write automated tests: Android Basics with Compose

### ISSUE THREAD

**Issue by abdellatifdarmellah** [google-developer-training/basic-android-kotlin-compose-training-tip-calculator#30]
![error](https://user-images.githubusercontent.com/76949906/196925631-5c0d74fb-6365-41b7-b15d-79653fd70745.PNG)
I am facing this error, I looked for the solution but I didn't find anything helpful, I guess the problem is with my phone 
anyway I need a help 
Thank you

**Comment by ifanzalukhu97** [comment]
@abdellatifdarmellah it's the same issue with #15, and there, already explain why the problem happen

**Comment by divyanshdxn** [comment]
@abdellatifdarmellah  would you consider closing this issue, as it is already tracked on https://github.com/google-developer-training/basic-android-kotlin-compose-training-tip-calculator/issues/15 ?

**Comment by android-dev-lxl** [comment]
This should be fixed now
