### ISSUE TITLE
Intro to state in Compose: Android Basics with Compose

### ISSUE THREAD

**Issue by majusmiles** [google-developer-training/basic-android-kotlin-compose-training-tip-calculator#41]
**URL of codelab**

**In which task and step of the codelab can this issue be found?**

**Describe the problem**

I don't think it's your code problem, it may by my AS setting, or something on mu side, but I have problem with your code, even after coping it from the website. 
I just can't make  .align working. Should I import or install something? 

Thank you 

**Steps to reproduce?**

**Versions**
Last AS version

**Additional information**

**Comment by android-dev-lxl** [comment]
@majusmiles 
Thank you for reaching out to us. 

Could you please give us some more context like:

- File name
- Task name
- Code snippet 

So we could help you with this.

**Comment by osuleymanova** [comment]
Closing this issue, since there is no user's reply.
