### ISSUE TITLE
Write automated tests: Android Basics with Compose

### ISSUE THREAD

**Issue by gensart-ai** [google-developer-training/basic-android-kotlin-compose-training-tip-calculator#42]
Hello, I'm Genes, from Indonesia 🇮🇩 ,

It's so nice to have an Android Basics with Compose material to learn for free !. Android Compose beginner like me will have good practice to learn Compose so easily.

Sorry for my english if seems a bit confusing hehe,
OK to the point, i think i have experienced some issue with your codelab at `Write automated tests` at Section `Write a local test` and `Write an instumentation test` and i think it's important to tell you all. On there, the material seems used the `NumberFormat` class for `assertEquals()` and `assertExists()` method. But the material just showed it on `Dollar` signs, while in my place now, Indonesia/Jakarta, the Android Studio didn't give any dollar sign that may have an impact on `assertEquals` and `assertExists` method. If i may to give some suggestion, can you provide some information in a current codelab that different countries/area may affect the NumberFormat returns.

As it is, any attentions to this would be appreciated for us all who wants to learn Compose in a great way in Google.
Cheers.

**Comment by osuleymanova** [comment]
Hello @gensart-ai,

Thank you for reaching out to us and sharing your feedback.
As for the currency convertor, please refer to the code snippet updated:

![Screenshot 2023-01-30 at 9 22 59 AM](https://user-images.githubusercontent.com/86437155/215549128-ec2da860-2882-4ad3-a97b-8bf4fb3ab407.png)

Be sure that import java.text.NumberFormat is imported.
