### ISSUE TITLE
Calculate a custom tip: Android Basics with Compose  

### ISSUE THREAD

**Issue by muggama** [google-developer-training/basic-android-kotlin-compose-training-tip-calculator#44]
**URL of codelab**

**In which task and step of the codelab can this issue be found?**

![Screenshot_20221126-211656_Tip Time](https://user-images.githubusercontent.com/50515126/204101101-d8c6afcb-3532-41da-870c-962404da5f28.jpg)

**Steps to reproduce?**
1. Go to...
2. Click on...
3. See error...

**Versions**
_Android Studio version:_ 
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

keyboardOptions = KeyboardOptions.Default.copy(
                keyboardType = KeyboardType.Number,
                imeAction = ImeAction.Next
            )
it looks like this for samsung S8 some buttons are missed

**Comment by android-dev-lxl** [comment]
@muggama 
Thank you for reaching out to us.
What buttons are missing, this is numeric keyboard to enter numbers in the input field.

**Comment by muggama** [comment]
It looks different on Redmi Note 8
![Screenshot_2023-04-07-16-04-15-439_com example tiptime](https://user-images.githubusercontent.com/50515126/230607452-0d22bef0-69db-4430-bd8d-c19f375c4d6f.jpg)

**Comment by android-dev-lxl** [comment]
@muggama 
Thank you for the reply. This keyboard is controlled by OEM, the manufacture. 
This is your next button, which we are configuring in the codelab
<img width="102" alt="image" src="https://github.com/google-developer-training/basic-android-kotlin-compose-training-tip-calculator/assets/24260141/50758999-2cf3-4332-808a-abbd7c207787">
