### ISSUE TITLE
Typo in Intro to state in Compose: Android Basics with Compose

### ISSUE THREAD

**Issue by varad64** [google-developer-training/basic-android-kotlin-compose-training-tip-calculator#45]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-compose-using-state?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-compose-unit-2-pathway-3%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-compose-using-state#7

**In which task and step of the codelab can this issue be found?**
Task - 8 : Use remember function to save state
Step - Step 4

**Describe the problem**
In the note at the end of step 4, there is a typo.

Original:
The amountInput is the mutable state being tracked by the Compose, recomposition is scheduled. The EditNumberField() composable function is recomposed. Since you are using remember { } the change survives the recomposition, that is the state is not re-initialized to "".

The above paragraph's last sentence should be corrected to "that is why the state is not re-initialized to ""."

**Steps to reproduce?**
1. Go to...  https://developer.android.com/codelabs/basic-android-kotlin-compose-using-state?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-compose-unit-2-pathway-3%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-compose-using-state#7
2. Click on... 
3. See error...

**Versions**
_Android Studio version:_ 
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by johnshea** [comment]
Hi @varad64 

Thank you for pointing this out and helping us to improve the course.

I shared your suggestion with the team.

Hope you are enjoying the course!

Regards.
