### ISSUE TITLE
Write automated tests: Android Basics with Compose

### ISSUE THREAD

**Issue by folsze** [google-developer-training/basic-android-kotlin-compose-training-tip-calculator#46]
There is no such "test" nor "androidTest" folder:
![image](https://user-images.githubusercontent.com/81622754/206176230-85799d8b-3be8-407f-b03c-b020fe3dc989.png)

in the src/main directory of the repo provided that's to be used for this

Section:
https://developer.android.com/codelabs/basic-android-kotlin-compose-write-automated-tests?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-compose-unit-2-pathway-3%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-compose-write-automated-tests#3

**Comment by osuleymanova** [comment]
Hello @folsze,

Thank you for reaching out to us. 
Please be sure that you opened the Project pane where you should find both directories androidTest and test:

![Screenshot 2023-01-24 at 4 30 43 PM](https://user-images.githubusercontent.com/86437155/214453685-eb6b1041-7f51-43d8-89b5-348b1194a7be.png)

If you are still having trouble finding directories, please feel free to reopen the issue with the attached screenshots.
