### ISSUE TITLE
Write automated tests: Android Basics with Compose

### ISSUE THREAD

**Issue by folsze** [google-developer-training/basic-android-kotlin-compose-training-tip-calculator#47]
https://developer.android.com/codelabs/basic-android-kotlin-compose-write-automated-tests?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-compose-unit-2-pathway-3%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-compose-write-automated-tests#4

Instead of:
composeTestRule.onNodeWithText("Tip Amount: $2.00").assertExists()

do:
composeTestRule.onNodeWithText("Tip amount: $2.00").assertExists()

(small letter a)

Since the strings.xml defines it as such

**Comment by osuleymanova** [comment]
Hello @folsze,

Thank you for reaching out to us. The code is correct, please refer to the image below:

![Screenshot 2023-01-24 at 2 32 01 PM](https://user-images.githubusercontent.com/86437155/214435901-47985b35-1a9a-4e2e-a0d4-1daa8b1d92b6.png)

**Comment by DemisChan** [comment]
Actualy the code still is with a capital A ...very confusing it took me 1 day to see my problem, thanx to this post.
