### ISSUE TITLE
Write automated tests: 4. Write a local test

### ISSUE THREAD

**Issue by mohiqbalrafsanjani** [google-developer-training/basic-android-kotlin-compose-training-tip-calculator#48]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-compose-write-automated-tests?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-compose-unit-2-pathway-3%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-compose-write-automated-tests#3

**In which task and step of the codelab can this issue be found?**
![image](https://user-images.githubusercontent.com/21128346/206209532-c49f0845-e939-4d7f-b78b-f2688cf33e04.png)

**Describe the problem**
This need a better instructions, should have "replace @" or "remove @ then add @" annotations, if i had to add @ VisibleForTesting , i should not have to remove @ Composable , i just add it to the bottom of @ Composable.

If that happen, this issue leads error in TipCalculatorTests.kt file, which the error need @ Composable and leads another error after the test runs.

**Comment by android-dev-lxl** [comment]
@mohiqbalrafsanjani 
Thank you for reaching out to us.

`CalculateTip` is not a Composble function. So there should not be @Composable on it. 

https://github.com/google-developer-training/basic-android-kotlin-compose-training-tip-calculator/blob/27e091b30590b15227b2c7f78ee43c06b546229e/app/src/main/java/com/example/tiptime/MainActivity.kt#L181

**Comment by osuleymanova** [comment]
Hello @mohiqbalrafsanjani,
 
Closing this issue, since there is no further response.
Please create a new one, if you need help.
All the best learning Android.
