### ISSUE TITLE
Calculate a custom tip: Android Basics with Compose  

### ISSUE THREAD

**Issue by Toren1esk19** [google-developer-training/basic-android-kotlin-compose-training-tip-calculator#49]
**In which task and step of the codelab can this issue be found?**
3 starer app overview

**Describe the problem**
In task 3,"Cost of Service" has already been changed to "Bill Amount", but solution code doesn't show it. So is the string in next task, which cause tests fails if follow these steps instead of download.

**Comment by osuleymanova** [comment]
Hello @Toren1esk19,

Thank you for contacting us and sharing your feedback. The repository has been recently updated so no more errors should be observed. The code snippet with the solution code is updated as well.
