### ISSUE TITLE
Calculate a custom tip: Android Basics with Compose  

### ISSUE THREAD

**Issue by ankurshaswat** [google-developer-training/basic-android-kotlin-compose-training-tip-calculator#50]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-compose-calculate-tip?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-compose-unit-2-pathway-3%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-compose-calculate-tip#6

**In which task and step of the codelab can this issue be found?**
7.  Add a switch

**Describe the problem**
Incorrect label formatting for image of thumb and track.

**Comment by android-dev-lxl** [comment]
Hi @ankurshaswat 
Could you please help us understand what exactly is incorrect?

**Comment by osuleymanova** [comment]
Hello @ankurshaswat,

Closing this issue, since there is no issue description.
Please create a new one, if you need help.
All the best learning Android.
