### ISSUE TITLE
Write automated tests: Android Basics with Compose

### ISSUE THREAD

**Issue by joeShuff** [google-developer-training/basic-android-kotlin-compose-training-tip-calculator#51]
The "Solution Code" zip download downloads from the `main` branch which isn't the solution code.

It should be from the `test_solution` branch

**Comment by AAB999** [comment]
THANKS for that tip! Now i can continue with the codelab.... :-)

**Comment by osuleymanova** [comment]
Hello @joeShuff,

Thank you for reaching out to us. The "Download zip" link is updated. You can always clone the repo with the correct branch by following git commands provided in the section"Get the solution code."

![Screenshot 2023-01-24 at 2 09 40 PM](https://user-images.githubusercontent.com/86437155/214432272-e268a867-2ed2-4584-a160-ab76d44abd03.png)
