### ISSUE TITLE
Calculate a custom tip: Android Basics with Compose  

### ISSUE THREAD

**Issue by newpaper818** [google-developer-training/basic-android-kotlin-compose-training-tip-calculator#57]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-compose-calculate-tip?hl=ko&continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-compose-unit-2-pathway-3%3Fhl%3Dko%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-compose-calculate-tip#4

**In which task and step of the codelab can this issue be found?**
EditNumberField() 함수에서 focusManager라는 val 변수를 추가하고 LocalFocusManager.current 속성 값을 할당합니다.

**Describe the problem**
EditNumberField() 함수에서 focusManager라는 val 변수를 추가하고 LocalFocusManager.current 속성 값을 할당합니다.
to
TipTimeScreen() 함수에서 focusManager라는 val 변수를 추가하고 LocalFocusManager.current 속성 값을 할당합니다.

**Steps to reproduce?**
1. Go to...
2. Click on...
3. See error...

**Versions**
_Android Studio version:_ 
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by osuleymanova** [comment]
Hello @newpaper818,

Thank you for reaching out to us and reporting this issue. It is fixed and published.
