### ISSUE TITLE
Write automated tests: Android Basics with Compose (Test fails if you don't specify Locale.US as a parameter to getCurrencyInstance()

### ISSUE THREAD

**Issue by taked4** [google-developer-training/basic-android-kotlin-compose-training-tip-calculator#59]
## What happened?
TipCalculatorTests fails.

## Error message
expected:<[$2.00]> but was:<[¥2]>
Expected :$2.00
Actual   :¥2

## Solution
Specify the `Locale.US` as a parameter to `getCurrencyInstance()` of the `calculateTip()` function like this:
`return NumberFormat.getCurrencyInstance(Locale.US).format(tip)`

## Reason (guessing)
I live in Japan.
So default locale is Locale.JAPAN
(But I don't know why emulator shows "$2.00" without specifying Locale.US)

## Code
MainActivity.kt line:135-145
```kotlin
@VisibleForTesting
internal fun calculateTip(amount: Double, tipPercent: Double = 15.0, roundUp: Boolean): String {
    var tip = tipPercent / 100 * amount
    if(roundUp) {
        tip = kotlin.math.ceil(tip)
    }
    return NumberFormat.getCurrencyInstance(Locale.US).format(tip)
}
```

**Comment by osuleymanova** [comment]
Hello @taked4,

Thanks for reaching out to us and sharing your concern. The issue is fixed and closed.
