### ISSUE TITLE
Calculate a custom tip: Android Basics with Compose  

### ISSUE THREAD

**Issue by a1danial** [google-developer-training/basic-android-kotlin-compose-training-tip-calculator#6]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-compose-calculate-tip?authuser=2&continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-compose-unit-2-pathway-3%3Fauthuser%3D2%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-compose-calculate-tip#4

**In which task and step of the codelab can this issue be found?**
Calculate a custom tip:
Step 5: Set keyboard actions

**Describe the problem**
"In the EditNumberField() function, add a val variable named focusManager and assign it a value of LocalFocusManager.current property:"
Val variable named focusManager not clearly specified as to where it should be added. Hence unsure of the accuracy of my code.

**Steps to reproduce?**
1. Go to...
2. Click on...
3. See error...
N/A

**Versions**
_Android Studio version:_ 
_API version of the emulator:_ 
N/A

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._
N/A

**Comment by michaelssim** [comment]
This is a mistake in the codelab.

It should say `TipTimeScreen()` instead of `EditNumberField()`. It should work. If it doesn't, just reply here.

fun TipTimeScreen() {
    var amountInput by remember { mutableStateOf("") }
    var tipInput by remember { mutableStateOf("") }

    val amount = amountInput.toDoubleOrNull() ?: 0.0
    val tipPercent = tipInput.toDoubleOrNull() ?: 0.0
    val tip = calculateTip(amount, tipPercent)
    **val focusManager = LocalFocusManager.current**

**Comment by osuleymanova** [comment]
@a1danial 
Thank you for reaching out to us. The typo is fixed and will be published soon:

![Screen Shot 2022-06-22 at 12 48 44 PM](https://user-images.githubusercontent.com/86437155/175125013-b84bc106-529a-4b28-8f1b-5428c0ed90ef.png)
