### ISSUE TITLE
Intro to state in Compose: Android Basics with Compose

### ISSUE THREAD

**Issue by MikeDeignan** [google-developer-training/basic-android-kotlin-compose-training-tip-calculator#60]
**URL of codelab**
 https://developer.android.com/codelabs/basic-android-kotlin-compose-using-state?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-compose-unit-2-pathway-3%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-compose-using-state#1

**In which task and step of the codelab can this issue be found?** 2 (Video)

**Describe the problem**
I have spent 5 times longer than normal to try and clearly understand what the gentleman is saying. I may have to throw-in the towel.
I have persevered to extreme impatience.)
(My native language is English. The video needs subtitles where this voice is used.)

**Steps to reproduce?** Listen to video
1. Go to...
2. Click on...
3. See error...

**Versions**
_Android Studio version:_ 
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by android-dev-lxl** [comment]
@MikeDeignan 
Thank you for your concern.
YouTube has a feature to auto generate the subtitles. 
To enable it please follow instructions provided here: https://support.google.com/youtube/answer/100078?hl=en&co=GENIE.Platform%3DDesktop
