### ISSUE TITLE
Write automated tests: Test folder missing

### ISSUE THREAD

**Issue by AAB999** [google-developer-training/basic-android-kotlin-compose-training-tip-calculator#61]
I have the same Problem as the first discribers. There is no "test" in the downloaded *zip file for the codelab. Can't continue....

And there is a solution from:
https://github.com/joeShuff

you have to download the zip from "solution" branch not the main branch....thanks to joe!

**Comment by osuleymanova** [comment]
Hello @AAB999,

Thank you for reaching out to us and sharing your concern. Please check out the latest fixes in the repository, as well as the codelab content update.
