### ISSUE TITLE
Inconsistent documentation on Calculate a custom tip: Android Basics with Compose 

### ISSUE THREAD

**Issue by amanbhurji** [google-developer-training/basic-android-kotlin-compose-training-tip-calculator#62]
**URL of codelab**
[Add a switch](https://developer.android.com/codelabs/basic-android-kotlin-compose-calculate-tip#6)

**In which task and step of the codelab can this issue be found?**
Step 7 and 15

**Describe the problem**
The instructions for in this codelab are inconsistent.

Step 7 adds `modifier` to the function definition for `RoundTheTipRow`
<img width="775" alt="Screenshot 2023-01-20 at 11 43 56 AM" src="https://user-images.githubusercontent.com/802094/213791808-d03790aa-a5da-4411-8636-987aef48e0d5.png">

Step 8 uses the `modifier` in follow up instructions to build the function

Step 15 presents the entire function and does not have the `modifier` parameter.
<img width="775" alt="Screenshot 2023-01-20 at 11 44 53 AM" src="https://user-images.githubusercontent.com/802094/213791976-a0fb867e-676b-4829-8ba3-59963c14836d.png">

**Comment by osuleymanova** [comment]
Hello @amanbhurji,

Thank you for reaching out to us. The typo is fixed and will be published soon.
