### ISSUE TITLE
Calculate a custom tip: Android Basics with Compose  

### ISSUE THREAD

**Issue by Rnscd** [google-developer-training/basic-android-kotlin-compose-training-tip-calculator#72]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-compose-calculate-tip?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-compose-unit-2-pathway-3%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-compose-calculate-tip#6

**In which task and step of the codelab can this issue be found?**
Add a switch - step 7

**Describe the problem**

In step 7, the name of the Function is wrong in the text, "In the RoundTipRow() function, add a roundUp parameter of Boolean type and an onRoundUpChanged lambda function that takes a Boolean and returns nothing:"

The correct name we give the function is "RoundTheTipRow()", which is consistent throughout the whole codelab except this paragraph.

**Comment by osuleymanova** [comment]
Hello @Rnscd,

Thank you for reaching out to us and reporting this typo. It is fixed and will be published soon.
