### ISSUE TITLE
Write automated tests: Android Basics with Compose

### ISSUE THREAD

**Issue by GabrielGomezGG** [google-developer-training/basic-android-kotlin-compose-training-tip-calculator#73]
En la parte donde escribimos los test de instrumentación. En vez de llamar "Bill Amount" llamamos a "Cost of Service"
``` kotlin
composeTestRule.onNodeWithText("Bill Amount")
      .performTextInput("10")

**Comment by android-dev-lxl** [comment]
@GabrielGomezGG 
This is fixed now. Thank you for your help.
