### ISSUE TITLE
Unresolved reference: createComposeRule()

### ISSUE THREAD

**Issue by coderinthenorth** [google-developer-training/basic-android-kotlin-compose-training-tip-calculator#75]
My code:
```Kotlin
package com.example.tipcalculatorapp

import com.example.tipcalculatorapp.ui.theme.TipCalculatorAppTheme
import org.junit.Rule
import org.junit.Test
import java.text.NumberFormat

class TipUITests {

    @get:Rule
    val composeTestRule = createComposeRule()

    @Test
    fun calculate_20_percent_tip() {
        composeTestRule.setContent {
            TipCalculatorAppTheme {
                TipCalculatorScreen()
            }
        }
        composeTestRule.onNodeWithText("Bill amount")
            .performTextInput("10")
        composeTestRule.onNodeWithText("Tip (%)").performeTextInput("20")
        val expectedTip = NumberFormat.getCurrencyInstance().format(2)
        composeTestRule.oneNodeWithText("Tip Amount: $expectedTip").assertExist("No node with this text was found")
    }
}
```

> #### Error message
> ../TipUITests.kt: (11, 27): Unresolved reference: createComposeRule

What is wrong with the code? Android Studio is not suggesting any imports for createComposeRule() either.

**Comment by osuleymanova** [comment]
Hello @coderinthenorth,

Thank you for reaching out to us. 
Be sure that you added the following import "import androidx.compose.ui.test.junit4.createComposeRule."

![Screenshot 2023-03-07 at 5 00 36 PM](https://user-images.githubusercontent.com/86437155/223591794-4b29ff59-4c1b-41ff-bdf4-9262553bcefa.png)

Please feel free to re-open the ticket if you still face the issue after that.
