### ISSUE TITLE
Write automated tests: Android Basics with Compose

### ISSUE THREAD

**Issue by kk-zu** [google-developer-training/basic-android-kotlin-compose-training-tip-calculator#81]
## where
5. Write an instrumentation test > Write the test > step 8

## what
This test want to assert that the tip amount is expected to display, but test code assert "No node with this text was found.".

## solution
```
composeTestRule.onNodeWithText("Tip Amount: $$expectedTip").assertExists("Tip Amount: $2.00")
```

## why
A dollar sign (`$`) means [String Templates](https://kotlinlang.org/docs/strings.html#string-templates) in kotlin.
So you must write `$` as a text and `$` as String Templates for `expectedTip`.

**Comment by DemisChan** [comment]
Not really the assertExists has only error message, it does not check the string inside it to be equal to the node text.
But I do get the same error and still havent resolved it:
`java.lang.AssertionError: No node with this text was found.
Reason: Expected exactly '1' node but could not find any node that satisfies: (Text + EditableText contains 'Tip Amount: $$2.00' (ignoreCase: false))`

**Comment by kk-zu** [comment]
@DemisChan Thank you.
Sorry. It is my mistake.
> Not really the assertExists has only error message

And, I do not understand that `expectedTip` return tip with `$`.
So the code that document is absolutely correct.

I close this issue.
