### ISSUE TITLE
Intro to state in Compose: Android Basics with Compose

### ISSUE THREAD

**Issue by DangXuanThong** [google-developer-training/basic-android-kotlin-compose-training-tip-calculator#96]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-compose-using-state

**In which task and step of the codelab can this issue be found?**
At task 11 and first step of "Use the calculateTip() function"

**Describe the problem**
In step 1 it should be in EditNumberField() function, not TipTimeScreen() function

**Additional information**
![image](https://user-images.githubusercontent.com/89197317/233846988-17b0c0db-1d4d-49e6-9697-743ae47f82e4.png)

**Comment by android-dev-lxl** [comment]
@DangXuanThong 
This is fixed now. Thank you for your help. 
https://github.com/google-developer-training/basic-android-kotlin-compose-training-tip-calculator/issues/97
