### ISSUE TITLE
Calculate a custom tip: Android Basics with Compose  

### ISSUE THREAD

**Issue by tibolanneau** [google-developer-training/basic-android-kotlin-compose-training-tip-calculator#99]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-compose-calculate-tip?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-compose-unit-2-pathway-3%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-compose-calculate-tip#4

**In which task and step of the codelab can this issue be found?**
5.4
6.3

**Describe the problem**
in example: 
fun EditNumberField(
    @StringRes label: Int,
    keyboardOptions: KeyboardOptions,
    value: String,
    onValueChange: (String) -> Unit,
)

in my code: 
fun EditNumberField(
    @StringRes label: Int,
    keyboardOptions: KeyboardOptions,
    value: String,
    onValueChange: (String) -> Unit,
    modifier: Modifier = Modifier
)

so "    modifier: Modifier = Modifier" is missing in the example.

**Steps to reproduce?**
N/a

**Versions**
_Android Studio version:_ flamingo (latest)
_API version of the emulator:_ 21 (5.0)

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._
/

**Comment by android-dev-lxl** [comment]
@tibolanneau 
Thank you so much for reporting this issue. This is fixed and will be published soon.
